### ISSUE TITLE
expect_i18n doesn't work inside server functions

### ISSUE THREAD

**Issue by kakserpom** [mondeja/leptos-fluent#111]
^^

**Comment by mondeja** [comment]
Because the context is not inside the server, but in the client. Raises:
```
thread '<unnamed>' panicked at leptos-fluent/src/lib.rs:337:27:
I18n context is missing, use the leptos_fluent!{} macro to provide it.
```
Despite the context is created both sides, on SSR and CSR.

I'm not sure if it would be possible to set the context on server side using the web server frameworks, or if something like that is possible to do with Leptos. Do you know about an example of a server side context?

Anyways, it is even a good practice to translate something in your API? You can always store the translations in the client and return a code from the server function.

**Comment by kakserpom** [comment]
@mondeja In my particular use case I need to get a list of all languages (IDs) and the fallback language. I know I can just read ./locales dir, but it's not very neat.

**Comment by mondeja** [comment]
For languages:

- Pass them as argument to the server function, `expect_i18n().languages`. Pros: no memory in the server. Cons: more bandwidth usage.
- Read from the locales dir or your languages file. Pros: less bandwidth usage. Cons: slower, handcrafted.

For the fallback language, opened https://github.com/XAMPPRocky/fluent-templates/pull/71 to expose it from fluent_templates. The bandwidth usage would be really minimal in this case, so I would pass as an argument to the server function. After the release of that PR, it would be available at `expect_i18n().translations.fallback`.

I'm open to other alternatives but doesn't seem doable to store the whole translations context in the server, not even in other more complicated use cases.
